# Generated by assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_paymentoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentoption",
            name="account_number",
            field=models.CharField(default="", max_length=128, blank=True),
        ),
    ]
