# Generated by Django 6.0.5 on 2026-05-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_account_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentoption',
            options={'verbose_name': 'Payment Setting', 'verbose_name_plural': 'Payment Settings'},
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number to display to users', max_length=128),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='bkash_number',
            field=models.CharField(blank=True, help_text='Legacy bKash number to display to users', max_length=64),
        ),
    ]
