# Generated by assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_heading', models.CharField(blank=True, default='Travel better with MyTrip', max_length=200)),
                ('hero_subheading', models.TextField(blank=True, default='Search flights, hotels and curated travel packages — plan and book in a few clicks.')),
                ('search_placeholder', models.CharField(blank=True, default='Search destinations, flights, hotels...', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
