# Generated by Django 6.0.5 on 2026-05-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_siteoption_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteoption',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
