# Generated by Django 6.0.5 on 2026-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
