# Generated by Django 6.0.5 on 2026-05-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/heroes/'),
        ),
        migrations.AddField(
            model_name='package',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='packages/logos/'),
        ),
    ]
