# Generated by Django 6.0.5 on 2026-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/heroes/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/logos/'),
        ),
    ]
