# Generated by Django 6.0.5 on 2026-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='flights/heroes/'),
        ),
    ]
