# Generated by Django 5.2.15 on 2026-07-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_hero_image'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='places.place'),
        ),
    ]
